# Generated by Django 4.0.8 on 2022-11-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRegistrar',
        ),
    ]
